### ISSUE TITLE
Many Open Pull Requests

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework3G4#104]
I see you still have many pull requests remaining. You should make sure to handle these before the deadline to ensure that your project is fully complete and you receive maximum credit.

**Comment by poojashresthacode** [comment]
Yeah, working on that, but all are sending pull requests at the last minute and it takes time to review the pull request. However, working on that since morning.

**Comment by Mosaddeq107** [comment]
Yes, accept those requests or reject them if they make conflicts.

**Comment by poojashresthacode** [comment]
Yeah, doing so.
