### ISSUE TITLE
About Plot

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework3G4#23]
@sharmistharanit 
@poojashresthacode 
What about the bar graph in the code, is it necessary to add there or not, please suggest me?

**Comment by poojashresthacode** [comment]
I think it is better to put the graph in documentation part.

**Comment by sharmistharanit** [comment]
In question, he did not ask for the plot. Is he?

**Comment by tirthbha** [comment]
@sharmistharanit You can add a photo to the documentation by simply adding files shown at the bottom of your documentation page. For this you need to take a screenshot of the graph and save the file as png.

**Comment by sharmistharanit** [comment]
Ok I will do that. Thank you @tirthbha
