### ISSUE TITLE
Picture required in the documentation.

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework3G4#39]
Hi G4 team,

I read about your project in the short_overview.md & trial_1_documentation files which is really good. It would have been much easier to visualize your problem if you guys put some pictures in it like you mentioned A to point E. So you are trying to solve velocities and energies of the curved, straight, or just some random paths?

**Comment by poojashresthacode** [comment]
So we are assuming that the body is moving horizontally in a straight path. And yeah, it's a nice idea!
