### ISSUE TITLE
python precision handling

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework3G4#42]
how did you handling precision of python? 
i use round()

**Comment by poojashresthacode** [comment]
Yeah, we have not used any precision, but we need to do it.

**Comment by tirthbha** [comment]
> how did you handling precision of python? i use round()

Precision of python? Could you please explain what you mean?

**Comment by poojashresthacode** [comment]
@tirthbha So our answer has large floating numbers, we need to diminish it for easy understanding. I think the professor has explained it in the class. Am I right @LinxuanHu ?? Please add the precision term in your code too @tirthbha

**Comment by reshnashrestha** [comment]
Built-in round() Function:

This is the most straightforward way. You can use the round() function to round a floating-point number to a specified number of decimal places.

x = 3.14159
rounded_x = round(x, 2)  # Rounding to 2 decimal places
print(rounded_x)  # 3.14

**Comment by poojashresthacode** [comment]
Hey reshna. So in this case we have to round off each value separately. Can't we do this for the whole answer at once by writing the code?

**Comment by reshnashrestha** [comment]
Yeah pooja I was thinking the same. If you know something let me know.

**Comment by tirthbha** [comment]
I don't think so, we have to do it independently for each result
________________________________

**Comment by poojashresthacode** [comment]
Okay
