### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework3G4#45]
@sharmistharanit, Are you referring following mentioned things for the documentation part?

The documentation should include the output of pylint (https://pypi.org/project/pylint/), pycodestyle (https://pycodestyle.pycqa.org/en/latest/intro.html) or for jupyter notebooks (https://github.com/mattijn/pycodestyle_magic)

**Comment by sharmistharanit** [comment]
How do I do taht.

**Comment by poojashresthacode** [comment]
I am figuring it out too.
