### ISSUE TITLE
Pylint

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework3G4#46]
What is the meaning of pylint?

**Comment by sharmistharanit** [comment]
Can anyone please tell me?

**Comment by poojashresthacode** [comment]
The documentation should include the output of pylint (https://pypi.org/project/pylint/), pycodestyle (https://pycodestyle.pycqa.org/en/latest/intro.html) or for jupyter notebooks (https://github.com/mattijn/pycodestyle_magic)   You can go through this and also you can use resources for better understanding.

**Comment by sharmistharanit** [comment]
ok Thanks.
