### ISSUE TITLE
Three Unit tests

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework3G4#50]
Hi all,
 I got to see three unit tests file in your main repository with same commit message. I am unable to find the difference with those. It would be easier for us know the changes you made if you have different commit messages for different unit test files.

**Comment by poojashresthacode** [comment]
The same commit message is because I have edited those codes for the same mistakes and I have defined the function in all those three unit tests. So, it has the same commit msg because the same mistakes were resolved in each unit teat.
