### ISSUE TITLE
Why did you choose to plot your data as a bar graph?

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework3G4#52]

**Comment by poojashresthacode** [comment]
Yeah, I think it will show the proper interpretation of our data. But, if you have any other way which is more influential than this, you can share it with us. Your effort will be highly appreciated.

**Comment by poojashresthacode** [comment]
Oh, you have already done it. Thankyou!

**Comment by sharmistharanit** [comment]
For better understanding, we are going to plot it.

**Comment by uarif** [comment]
I checked your plot, it makes more sense and more understandable with the plot.
