### ISSUE TITLE
Why so many files?

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework3G4#57]
Is there a reason why you create new files instead of just commiting to the old one?

**Comment by uarif** [comment]
Yes, Actually, I created the same issue in one of the groups.. They have many files, its confusing, but I guess its not finalized yet 🤔

**Comment by sharmistharanit** [comment]
We have created one documentation file for trial as I did not know how to do. The final documentation file contains everything.

**Comment by uarif** [comment]
Okay, I see, thank you, I guess to avoid confusions you should delete the other one right?.

**Comment by JustinJaniszewski** [comment]
Thanks for the clarification. I do also think unnecessary files should be deleted.
