### ISSUE TITLE
ENVIRONMENT..

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework3G4#61]
Which environment are you using for running the codes?

**Comment by uarif** [comment]
Okay, thank you, I am facing some issues in google colab that is why I asked

**Comment by poojashresthacode** [comment]
What kinds of issues are you facing, please share with us.

**Comment by tirthbha** [comment]
@uarif Can you let us to know about the issues that you have faced in google.colab?

**Comment by LinxuanHu** [comment]
@uarif Can you specify the issue you face

**Comment by poojashresthacode** [comment]
No discussion is going on here, so I am closing the issue.
