### ISSUE TITLE
Use Pylint output

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework3G4#67]
Hi all, 
We are supposed to include the output of pylint in our documentation, so you can run your main code using pylint like we did in class and see the errors or issues related to your code. Include the output you got  using pylint in  documentation.  Pylint are mostly preferred to see the issues in python code.

**Comment by reshnashrestha** [comment]
@pratibha77118 I believe that this group has added the output of pylint in their documentation.

**Comment by poojashresthacode** [comment]
Yeah, we have.
