### ISSUE TITLE
Naming of Files

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework3G4#68]
I noticed that some of your files don't follow the proper naming convention for python and markdown files (such as outlined in PEP 8 https://peps.python.org/pep-0008/#package-and-module-names). I made a pull request to rename the markdown file yesterday (#53), but the other python files would benefit from this too to improve readability (and if anyone else still needs commits for this homework this is useful for that too.)

**Comment by poojashresthacode** [comment]
Appreciated.
