### ISSUE TITLE
CM function

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework3G4#7]
What about the projectile motion to find the time of flight for an object projected horizontally?
@poojashresthacode @sharmistharanit

**Comment by sharmistharanit** [comment]
Yes, that is a good idea. Let's do that.

**Comment by poojashresthacode** [comment]
We are using kinetic energy calculation.

**Comment by poojashresthacode** [comment]
Let's do something simple. In projectile motion we should take account the vertical and horizontal motion which will be a bit complicated. Let's do a bit simple thing and learn from there. So Kinetic energy will be better option

**Comment by Pranjal-Srivastava-2023** [comment]
I have sent merge requests for both projectile motion and kinetic energy. You can have a look and use whichever works best for you. I think projectile motion is better because you can also plot it.

**Comment by tirthbha** [comment]
> I have sent merge requests for both projectile motion and kinetic energy. You can have a look and use whichever works best for you. I think projectile motion is better because you can also plot it.

We will consider your contribution to our work.
