### ISSUE TITLE
Generator Function

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework3G4#71]
@sharmistharanit 
I believe that we need to explain the generator function in the documentation. Can you please add it?

**Comment by sharmistharanit** [comment]
I do not think that I have to attach it documentation. It will be in the algorithm part. Right? @tirthbha

**Comment by poojashresthacode** [comment]
Yeah!! I just mean that we have to mention it in the documentation.

**Comment by tirthbha** [comment]
> I do not think that I have to attach it documentation. It will be in the algorithm part. Right? @tirthbha

You have to mention a brief explanation about generator in the documentation.

**Comment by sharmistharanit** [comment]
I understood. I have done this. you can check now.
