### ISSUE TITLE
Final Documentation File

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework3G4#72]
@sharmistharanit 
[WorkDonebyMapAndLambda.md](https://github.com/sharmistharanit/23-Homework3G4/files/12807475/WorkDonebyMapAndLambda.md)

I have found this link in the documentation file created by you.  When I clicked the link, I found it empty. Please check it once where it went wrong.

**Comment by sharmistharanit** [comment]
Sure. I will check it.

**Comment by tirthbha** [comment]
Yeah there is nothing to find when opened that link. @sharmistharanit

**Comment by poojashresthacode** [comment]
I think this issue is resolved.
