### ISSUE TITLE
pycodestyle checked your hw_work_done_G4.py

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework3G4#78]
Hi guys, I checked your python file with pycodestyle, it is throwing some suggestions for your code to improve the quality of code. Would you like to follow it? Here's the screenshot of it!
![image](https://github.com/ubsuny/23-Homework3G4/assets/144289804/c95bb7bb-f522-437a-8805-26cb70e40c56)

**Comment by poojashresthacode** [comment]
Great. But I think it would be better if you suggest us  the changes a bit earlier and we are now at the last hour. However, appreciated your suggestions. Will take care of it forward.
