### ISSUE TITLE
Functional Programming Concepts

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework3G4#8]
Can you briefly explain this ?

**Comment by poojashresthacode** [comment]
I don't know much but as I know, we have to use the functions mentioned in the question. This will make our coding concise and to the point. I think these functional programming are the way of writing code in manageable form.

**Comment by poojashresthacode** [comment]
Anything you know about this, please share. Your help will be highly appreciated.

**Comment by tirthbha** [comment]
> Can you briefly explain this ?

Our main intention to find the work done at different points along the way, by calculating the change in kinetic energy, where the final velocity for the first point becomes the initial velocity for the second point and hance overall workdone".
