### ISSUE TITLE
Help needed to resolve the issue of Group2

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework3G4#83]
We uploaded a new file that contains some changes. However, we found the following error after merging with the main repository.

![Screenshot from 2023-10-06 09-58-24](https://github.com/ubsuny/23-Homework3G4/assets/66480280/ae89353e-e0f3-4823-98d6-e2114e8c45e9)

**Comment by poojashresthacode** [comment]
The problem is so different. I will discuss this with other members and get back to you if I find anything helpful to you.

**Comment by Mosaddeq107** [comment]
We already fixed that.

**Comment by Mosaddeq107** [comment]
I appreciate your support.
