### ISSUE TITLE
importing module

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework3G4#92]
Hello,
when I try to separate the algorithm and run them via google Colab or any other platform it always returns that there's no module named algorithm.py

any ideas??

**Comment by poojashresthacode** [comment]
Have you created your own library module?

**Comment by tirthbha** [comment]
@yasmensarhan27 I think you have missed the command to write there (%%writefile file_name)

**Comment by yasmensarhan27** [comment]
solved thank you
