### ISSUE TITLE
Many Files Makes it Hard to Navigate

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework3G4#93]
I know it's a little close to the deadline, but it's a little cluttered with all of the different versions of files in your repository. Deleting the old versions would definitely make it easier to access the finalized versions if you have the time!

**Comment by poojashresthacode** [comment]
Thank you for the suggestion. Yeah! I am trying to do so, but if I delete those files, Then, I am afraid if it will show no contribution from the members whose files have been deleted.
